#!/bin/bash
# Wrapper script that run a command with pip packages installed

set -euxo pipefail

# Install requirements
python3 -m pip install --upgrade pip setuptools
while [ $# -ge 2 ];
do
    if [ "$1" == "-r" ];
    then
        python3 -m pip install -r requirements/$2-pip.txt
        shift
        shift
    else
        break
    fi
done

# Execute provided command line
echo "Executing \"$*\"..."
sh -c "$*"
