#!/bin/bash
# WARNING: make sure this is the same image as the one used in the pipeline

set -euxo pipefail

docker run -it --rm \
       -v $PWD:$PWD \
       -w $PWD \
       python:3.5 \
       $*
